#!/usr/bin/env python3
"""
Autoscientist Research Runner
Wraps karpathy/autoresearch to produce structured reports for OpenClaw workspace.
Features: Telegram notification + Google Drive upload (gws or gdrive).
"""

import os
import sys
import json
import argparse
import subprocess
from datetime import datetime
from pathlib import Path

try:
    from autoresearch import run_autoresearch
except ImportError:
    print("Error: autoresearch not installed.")
    print("Install with: pip install git+https://github.com/karpathy/autoresearch.git")
    sys.exit(1)

# Load workspace config for Telegram/Drive tokens
try:
    from dotenv import load_dotenv
    load_dotenv('/home/ubuntu/.openclaw/workspace/.env')
except:
    pass  # .env may not exist, we'll read from environment manually

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')
GDRIVE_FOLDER_ID = os.getenv('GDRIVE_REPORTS_FOLDER_ID')  # Google Drive folder ID

def send_telegram(message: str):
    """Send a message to Telegram chat."""
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        return False
    try:
        import requests
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        r = requests.post(url, json={"chat_id": TELEGRAM_CHAT_ID, "text": message, "parse_mode": "HTML"})
        return r.status_code == 200
    except:
        return False

def upload_via_gws(filepath: str) -> str | None:
    """Upload using gws CLI (workspace tool)."""
    if not GDRIVE_FOLDER_ID:
        return None
    cmd = f"gws drive +upload {filepath} --parent {GDRIVE_FOLDER_ID}"
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode == 0:
        try:
            data = json.loads(result.stdout)
            return data.get('id')
        except:
            pass
    return None

def upload_via_gdrive(filepath: str) -> str | None:
    """Fallback: upload using gdrive CLI."""
    if not GDRIVE_FOLDER_ID:
        return None
    cmd = f"gdrive files upload --parent {GDRIVE_FOLDER_ID} --name '{Path(filepath).name}' '{filepath}'"
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode == 0:
        import re
        match = re.search(r'id:\s*([a-zA-Z0-9_-]+)', result.stdout)
        if match:
            return match.group(1)
    return None

def upload_to_drive(filepath: str) -> str | None:
    """Try both gws and gdrive to upload."""
    file_id = upload_via_gws(filepath)
    if file_id:
        return file_id
    file_id = upload_via_gdrive(filepath)
    return file_id

def generate_report(question: str, output_dir: str = "reports"):
    """Run autoresearch and produce a markdown report."""
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M")
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    print(f"🔍 Starting research: {question}")
    results = run_autoresearch(question)
    
    md_lines = [
        f"# Autoscientist Research Report",
        f"**Question:** {question}",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**Sources consulted:** {len(results.get('sources', []))}",
        "",
        "## Summary",
        results.get("summary", "No summary generated."),
        "",
        "## Detailed Findings",
    ]
    
    for i, source in enumerate(results.get("sources", []), 1):
        md_lines.append(f"### Source {i}: {source.get('title', 'Untitled')}")
        md_lines.append(f"- URL: {source.get('url', 'N/A')}")
        md_lines.append(f"- Excerpt: {source.get('excerpt', '')[:500]}...")
        md_lines.append("")
    
    md_lines.extend([
        "## Conclusions",
        results.get("conclusion", "Research complete."),
        "",
        "---",
        "*Generated by Autoscientist agent*"
    ])
    
    report_file = output_path / f"research_{timestamp}.md"
    report_file.write_text("\n".join(md_lines))
    print(f"✅ Report saved: {report_file}")
    
    # Telegram notification
    telegram_msg = f"📄 Autoscientist report ready\n<b>{question}</b>\n📁 {report_file.name}"
    if send_telegram(telegram_msg):
        print("📨 Telegram notification sent")
    else:
        print("⚠️ Telegram not configured or failed")
    
    # Google Drive upload
    if GDRIVE_FOLDER_ID:
        file_id = upload_to_drive(str(report_file))
        if file_id:
            drive_link = f"https://drive.google.com/file/d/{file_id}"
            print(f"📤 Uploaded to Drive: {drive_link}")
            # Also send Drive link via Telegram
            if TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID:
                send_telegram(f"📤 <a href=\"{drive_link}\">View report in Drive</a>")
        else:
            print("⚠️ Drive upload failed (gws/gdrive error)")
    
    return str(report_file)

def main():
    parser = argparse.ArgumentParser(description="Autoscientist Research Agent")
    parser.add_argument("question", help="Research question to investigate")
    parser.add_argument("--output-dir", default="reports", help="Directory to save reports")
    args = parser.parse_args()
    
    report_path = generate_report(args.question, args.output_dir)
    print(f"📄 Report: {report_path}")

if __name__ == "__main__":
    main()
